### ISSUE TITLE
missing plugin installer

### ISSUE THREAD

**Issue by KRDucky** [jarangmandi/BFSGSimCom#62]
I did not see any releases and no real way to build the plugin. The make plugin script is missing a bunch of files.

**Comment by jarangmandi** [comment]
There are no releases posted here - although I probably could. It IS available for download from the TeamSpeak site although they've been sitting on the new version for an age. It's also available for download from here... 

https://bfsg.blob.core.windows.net/bfsgsimcom/BFSGSimCom_win32.ts3_plugin for the 32-bit version
https://bfsg.blob.core.windows.net/bfsgsimcom/BFSGSimCom_win64.ts3_plugin for the 64-bit version

The way to build the plugin is to open the solution (.sln) file in Visual Studio and build from there. I've just done it with VS2019 on a clean machine and it builds fine. How are you trying to do it?

**Comment by jarangmandi** [comment]
That said - it IS dependent on the presence of a Qt environment and build tools by virtue of that being the underlying technology used by TeamSpeak. The current version is build against Qt version 5.12.3.

The location of those tools on your system will need to be set in the user macros defined in the BFSGSimCom property pages (accessible through the Property Manager in VS).

**Comment by KRDucky** [comment]
I was just running the Build script inside the installer folder. I put the sqlite.exe file in the folder as well.

**Comment by jarangmandi** [comment]
The installer collates all of the necessary files that are prepared by the Build step. If the build hasn't been run, those files won't be there.
