### ISSUE TITLE
XPUIPC Teamspeak 3 and BFSGSimCom - CIXVFR Logger Compatibility

### ISSUE THREAD

**Issue by DKH3491** [jarangmandi/BFSGSimCom#65]
Hello,I am trying to mach my com radio frequencies to teamspeak using a plugin for Teamspeak 3 called BFSGSimCom but when teampspeak opens it says is connected to the sim, in this case X Plane 11 but doesn't read the values from the radio frequencies it just stays in zeros, my question is how does XPUIPC read these values, from the dataref?
It works flawlessly with MFS2020 and P3D using FSUIPC
![(%B5CJD4I7AY8{W L198CJE](https://user-images.githubusercontent.com/119775820/205476272-854f7494-e627-4972-a0bd-3d0c8eca26d7.png)

**Comment by jarangmandi** [comment]
Hi,

Can you confirm which version of BFGSimCom you're using please? If it's not at least version 0.14.0, I'd recommend downloading that from this site.

I believe that your problem should be resolved by adding the following to the XPUIPCOffsets.cfg file (in the <XP folder>\resources\plugins\XPUIPC folder)

```
#
# Added by AP for XP 8.33Khz processing.
#
Dataref	com1_freq_833	sim/cockpit2/radios/actuators/com1_frequency_hz_833	int
Dataref	com2_freq_833	sim/cockpit2/radios/actuators/com2_frequency_hz_833	int
Dataref	com1_stby_freq_833	sim/cockpit2/radios/actuators/com1_standby_frequency_hz_833	int
Dataref	com2_stby_freq_833	sim/cockpit2/radios/actuators/com2_standby_frequency_hz_833	int
Offset	0x05c4	UINT32	3	r	$com1_freq_833 1000 *
Offset	0x05c8	UINT32	3	r	$com2_freq_833 1000 *
Offset	0x05cc	UINT32	3	r	$com1_stby_freq_833 1000 *
Offset	0x05d0	UINT32	3	r	$com2_stby_freq_833 1000 *
```

**Comment by DKH3491** [comment]
Thank you very much. It can use it normally
